### ISSUE TITLE
More CI tests

### ISSUE THREAD

**Issue by PeyTy** [hexalang/hexa#30]
Progress

- [x] `node --trace-uncaught`
- [x] Other tests
- [x] CI failure on tests build failure
- [ ] `msbuild` aka MSVC of win32/posix demos.
  - [ ] Must use C (not C++) with C11 standard, if possible.
  - [ ] Should *also* build with C++11 *and* C++2x (latest standard) modes (for regressions)
  - [ ] 32-bit and 64-bit
- [ ] CI failure on `msbuild` failure
- [x] CI logs should provide Hexa compiler stdout/stderr (like `[Building The Hexa Compiler]...`)
- [ ] Timeouts for builds (sometimes build may go infinite loop). For example 3 minutes should be enough for now.
- [x] Add Linux (64-bit) and macOS (with Xcode enabled) builds/artifacts, possibly within one action `build-all`
- [x] Merge libgen build into one action if it makes sense (separate build block within `build-all` for parallel)
- [x] Parallel execution of all build tasks
- [x] Action `test-all` which takes artifacts from `build-all` (if `build-all` succeeded) and builds tests from 2.

1. All `node.exe` invocations should use `--trace-uncaught` as the first argument like this `--trace-uncaught bootstrap.js hexa.json`. Node is very conservative on error origins without that feature.
2. More tests should be built after bootstrapping process:
```sh
test/lts/hello/hexa.json
examples/html-raytracer/hexa.json
test/normalizer/hexa.json
examples/node-platform/hexa.json
examples/native-win32/hexa.json
examples/native-posix/hexa.json + build the output (macos clang, windows msvc, linux gcc) (NO artifact needed)
```
3. CI should stop on any build error. Hexa reports non-zero error code on fail, zero on success.
4. Build `examples/native-win32/win32.c` (build only) with MSVC (like `libgen`). It is produced from `examples/native-win32/hexa.json`. **Same for POSIX demo.**
5. CI should stop on any MSVC build error.

**Comment by PeyTy** [comment]
@acidicMercury8 added timeouts bullet point
